
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- development

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'wimvanderveen/examplenode-docker'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build and Push
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(imageName)
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

  - job: Push
    displayName: Push
    steps:
     - task: Docker@2
       displayName: Push the image
       inputs:
         repository: $(imageName)
         command: 'push'
         tags: |
          $(tag)
