
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- development

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@1
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: Push
  displayName: Push image
  jobs:
  - job: Push
    displayName: Puah
    pool:
      vmImage: ubuntu-latest
    steps:
     - task: Docker@2
       displayName: Push the image
       inputs:
         repository: 'wimvanderveen/examplenode'
         command: 'push'
         tags: |
          $(tag)
